name: Set User Rewards

on:
  schedule:
    # Run once a day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  set-user-rewards:
    runs-on: ubuntu-latest

    steps:
      - name: Call Set Rewards API
        run: |
          response=$(curl -s -w "\n%{http_code}" -X GET \
            -H "x-api-key: ${{ secrets.API_KEY }}" \
            ${{ secrets.API_URL }}/user/rewards/set)

          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "Status code: $status_code"
          echo "Response body: $body"

          if [ "$status_code" -lt 200 ] || [ "$status_code" -ge 300 ]; then
            echo "API call failed with status code $status_code"
            exit 1
          fi
